allowBuilds:
<<<<<<< HEAD
  '@parcel/watcher': false
  esbuild: true
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
=======
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
>>>>>>> feature/frontend
